version: '3.8' # Adicione a versão do compose

services:
  redis:
    image: 'redis:alpine'

  mysql:
    image: 'mysql:5.7'
    working_dir: /application
    volumes:
      - '.:/application'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    ports:
      - '8082:3306'

  webserver:
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - '.:/application'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '8080:80'

  php-fpm:
    build: ./
    working_dir: /application
    volumes:
      - '.:/application'
